name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-GSu.png
    - assets/page-1/images/vector-aky.png
    - assets/page-1/images/vector-a3b.png
    - assets/page-1/images/vector-Miq.png
    - assets/page-1/images/vector-ySZ.png
    - assets/page-1/images/vector-WY1.png
    - assets/page-1/images/vector-4mf.png
    - assets/page-1/images/left.png
    - assets/page-1/images/left-DwX.png
    - assets/page-1/images/vector-YWD.png
    - assets/page-1/images/left-S73.png
    - assets/page-1/images/right-rrV.png
    - assets/page-1/images/left-yMK.png
    - assets/page-1/images/vector-BQ5.png
    - assets/page-1/images/right.png
    - assets/page-1/images/right-8tH.png
    - assets/page-1/images/left-89X.png
    - assets/page-1/images/vector-YBK.png
    - assets/page-1/images/vector-Ze9.png
    - assets/page-1/images/right-QPB.png
    - assets/page-1/images/vector-1xM.png
    - assets/page-1/images/left-aUy.png
    - assets/page-1/images/vector-hE9.png
    - assets/page-1/images/icons.png
    - assets/page-1/images/menu-item.png
    - assets/page-1/images/vector-Sdw.png
    - assets/page-1/images/menu-item-HUu.png
    - assets/page-1/images/vector-krd.png
    - assets/page-1/images/undrawspecsre546x-1.png
    - assets/page-1/images/left-6M7.png
    - assets/page-1/images/left-sLu.png
    - assets/page-1/images/icons-pjj.png
    - assets/page-1/images/right-BqB.png
    - assets/page-1/images/vector-9X7.png
    - assets/page-1/images/vector-y3X.png
    - assets/page-1/images/right-1wF.png
    - assets/page-1/images/vector-LC9.png
    - assets/page-1/images/vector-3Bf.png
    - assets/page-1/images/right-HxV.png
    - assets/page-1/images/vector-sNH.png
    - assets/page-1/images/menu-item-efs.png
    - assets/page-1/images/group-42.png
    - assets/page-1/images/vector-Z5j.png
    - assets/page-1/images/vector-S33.png
    - assets/page-1/images/vector-84H.png
    - assets/page-1/images/pexels-photo-6952421-2-bg.png
    - assets/page-1/images/menu-item-N6D.png
    - assets/page-1/images/pexels-photo-6952421-2.png
    - assets/page-1/images/vector-fTw.png
    - assets/page-1/images/vector-rC1.png
    - assets/page-1/images/vector-PVK.png
    - assets/page-1/images/vector-UMf.png
    - assets/page-1/images/undrawwelldonere3hpo-1.png
    - assets/page-1/images/ellipse-26-bg.png
    - assets/page-1/images/group-42-UUy.png
    - assets/page-1/images/vector-RTF.png
    - assets/page-1/images/vector-T2Z.png
    - assets/page-1/images/vector-QeV.png
    - assets/page-1/images/icons-eAV.png
    - assets/page-1/images/ellipse-32-bg.png
    - assets/page-1/images/states-of-avatar.png
    - assets/page-1/images/ellipse-13-bg.png
    - assets/page-1/images/ellipse-21-bg.png
    - assets/page-1/images/ellipse-12-bg.png
    - assets/page-1/images/vector-DDs.png
    - assets/page-1/images/vector-EEm.png
    - assets/page-1/images/states-of-avatar-Xv1.png
    - assets/page-1/images/vector-Ea5.png
    - assets/page-1/images/vector-9Mb.png
    - assets/page-1/images/vector-5Vs.png
    - assets/page-1/images/ellipse-14-bg.png
    - assets/page-1/images/group-42-nv5.png
    - assets/page-1/images/circle-button.png
    - assets/page-1/images/vector-qjF.png
    - assets/page-1/images/vector-x57.png
    - assets/page-1/images/ellipse-49.png
    - assets/page-1/images/ellipse-22-bg.png
    - assets/page-1/images/right-6eM.png
    - assets/page-1/images/vector-SCR.png
    - assets/page-1/images/group-38.png
    - assets/page-1/images/group-42-XjX.png
    - assets/page-1/images/vector-gMX.png
    - assets/page-1/images/vector-eJM.png
    - assets/page-1/images/right-3zh.png
    - assets/page-1/images/ellipse-25-bg.png
    - assets/page-1/images/ellipse-12-bg-AG1.png
    - assets/page-1/images/vector-yFw.png
    - assets/page-1/images/left-fdB.png
    - assets/page-1/images/ellipse-20-bg.png
    - assets/page-1/images/menu-item-HHK.png
    - assets/page-1/images/vector-qg5.png
    - assets/page-1/images/ellipse-14-bg-YFb.png
    - assets/page-1/images/ellipse-16-bg.png
    - assets/page-1/images/vector-6Ad.png
    - assets/page-1/images/ellipse-15-bg.png
    - assets/page-1/images/states-of-avatar-2KB.png
    - assets/page-1/images/ellipse-30-bg.png
    - assets/page-1/images/vector-oDT.png
    - assets/page-1/images/ellipse-25-bg-kuP.png
    - assets/page-1/images/ellipse-13-bg-yhT.png
    - assets/page-1/images/ellipse-19-bg.png
    - assets/page-1/images/vector-XTX.png
    - assets/page-1/images/auto-group-m9zs.png
    - assets/page-1/images/vector-zdw.png
    - assets/page-1/images/ellipse-28-bg.png
    - assets/page-1/images/group-38-qgV.png
    - assets/page-1/images/ellipse-13-bg-5KF.png
    - assets/page-1/images/n.png
    - assets/page-1/images/ellipse-31-bg.png
    - assets/page-1/images/ellipse-33-bg.png
    - assets/page-1/images/ellipse-17-bg.png
    - assets/page-1/images/ellipse-29-bg.png
    - assets/page-1/images/vector-4Cq.png
    - assets/page-1/images/ellipse-18-bg.png
    - assets/page-1/images/ellipse-24-bg.png
    - assets/page-1/images/ellipse-42-bg.png
    - assets/page-1/images/ellipse-27-bg.png
    - assets/page-1/images/ellipse-12-bg-jmT.png
    - assets/page-1/images/ellipse-24-bg-dkM.png
    - assets/page-1/images/states-of-avatar-mUM.png
    - assets/page-1/images/vector-jxD.png
    - assets/page-1/images/ellipse-23-bg.png
    - assets/page-1/images/ellipse-42-bg-oW9.png
    - assets/page-1/images/states-of-avatar-6tZ.png
    - assets/page-1/images/ellipse-49-SL9.png
    - assets/page-1/images/rectangle-56.png
    - assets/page-1/images/vector-bmB.png
    - assets/page-1/images/vector-aKb.png
    - assets/page-1/images/states-of-avatar-dXX.png
    - assets/page-1/images/states-of-avatar-Wfj.png
    - assets/page-1/images/vector-5Jq.png
    - assets/page-1/images/vector-9Tf.png
    - assets/page-1/images/vector-cvu.png
    - assets/page-1/images/create-a-group-button-default.png
    - assets/page-1/images/vector-DsX.png
    - assets/page-1/images/circle-button-R3f.png
    - assets/page-1/images/ellipse-20-bg-Tny.png
    - assets/page-1/images/ellipse-25-bg-ZsF.png
    - assets/page-1/images/ellipse-27-bg-iVF.png
    - assets/page-1/images/ellipse-28-bg-Gmf.png
    - assets/page-1/images/ellipse-22-bg-h1j.png
    - assets/page-1/images/ellipse-42-bg-LVw.png
    - assets/page-1/images/ellipse-15-bg-RGV.png
    - assets/page-1/images/vector-o3f.png
    - assets/page-1/images/states-of-avatar-L3b.png
    - assets/page-1/images/ellipse-14-bg-CLh.png
    - assets/page-1/images/left-xam.png
    - assets/page-1/images/ellipse-18-bg-3u3.png
    - assets/page-1/images/right-Qjb.png
    - assets/page-1/images/states-of-avatar-wmT.png
    - assets/page-1/images/circle-button-uCV.png
    - assets/page-1/images/vector-Fn9.png
    - assets/page-1/images/ellipse-16-bg-1WR.png
    - assets/page-1/images/states-of-avatar-Au7.png
    - assets/page-1/images/vector-dGu.png
    - assets/page-1/images/ellipse-26-bg-LBK.png
    - assets/page-1/images/ellipse-33-bg-m5T.png
    - assets/page-1/images/vector-uRs.png
    - assets/page-1/images/menu-item-FVj.png
    - assets/page-1/images/create-a-group-button.png
    - assets/page-1/images/vector-U6u.png
    - assets/page-1/images/ellipse-12-bg-whj.png
    - assets/page-1/images/rectangle-56-DSq.png
    - assets/page-1/images/left-9Uu.png
    - assets/page-1/images/vector-Rub.png
    - assets/page-1/images/ellipse-28-bg-4Hf.png
    - assets/page-1/images/rectangle-56-bg.png
    - assets/page-1/images/left-LZX.png
    - assets/page-1/images/group-30.png
    - assets/page-1/images/vector-Ah7.png
    - assets/page-1/images/vector-PkD.png
    - assets/page-1/images/ellipse-32-bg-W65.png
    - assets/page-1/images/group-28.png
    - assets/page-1/images/ellipse-13-bg-hLu.png
    - assets/page-1/images/vector-qbX.png
    - assets/page-1/images/ellipse-27-bg-5ih.png
    - assets/page-1/images/vector-sEZ.png
    - assets/page-1/images/ellipse-26-bg-xmF.png
    - assets/page-1/images/vector-VWq.png
    - assets/page-1/images/ellipse-20-bg-Vms.png
    - assets/page-1/images/vector-WqP.png
    - assets/page-1/images/menu-item-sTw.png
    - assets/page-1/images/ellipse-33-bg-v7j.png
    - assets/page-1/images/ellipse-14-bg-Wk9.png
    - assets/page-1/images/trash.png
    - assets/page-1/images/ellipse-28-bg-mgd.png
    - assets/page-1/images/right-3S9.png
    - assets/page-1/images/ellipse-32-bg-1fo.png
    - assets/page-1/images/ellipse-32-bg-qHT.png
    - assets/page-1/images/ellipse-27-bg-e9P.png
    - assets/page-1/images/vector-gnm.png
    - assets/page-1/images/vector-fMj.png
    - assets/page-1/images/trash-2zu.png
    - assets/page-1/images/ellipse-22-bg-9zy.png
    - assets/page-1/images/trash-DWy.png
    - assets/page-1/images/menu-item-AJD.png
    - assets/page-1/images/ellipse-12-bg-ZUm.png
    - assets/page-1/images/ellipse-16-bg-7TP.png
    - assets/page-1/images/trash-t6m.png
    - assets/page-1/images/vector-L3j.png
    - assets/page-1/images/vector-yvq.png
    - assets/page-1/images/right-8Hw.png
    - assets/page-1/images/vector-TnZ.png
    - assets/page-1/images/menu-item-q1j.png
    - assets/page-1/images/menu-item-aV7.png
    - assets/page-1/images/ellipse-18-bg-XfF.png
    - assets/page-1/images/icons-fjP.png
    - assets/page-1/images/trash-cuX.png
    - assets/page-1/images/line-4.png
    - assets/page-1/images/vector-i5P.png
    - assets/page-1/images/group-31.png
    - assets/page-1/images/icons-settingsfilled24px.png
    - assets/page-1/images/trash-ZrH.png
    - assets/page-1/images/group-31-kDw.png
    - assets/page-1/images/icons-n9o.png
    - assets/page-1/images/ellipse-26-bg-wgd.png
    - assets/page-1/images/ellipse-18-bg-4rD.png
    - assets/page-1/images/group-30-KN1.png
    - assets/page-1/images/icons-U9f.png
    - assets/page-1/images/ellipse-15-bg-mA1.png
    - assets/page-1/images/group-42-W3s.png
    - assets/page-1/images/trash-z8Z.png
    - assets/page-1/images/ellipse-22-bg-FqB.png
    - assets/page-1/images/ellipse-24-bg-Hmb.png
    - assets/page-1/images/vector-uwP.png
    - assets/page-1/images/ellipse-13-bg-B1j.png
    - assets/page-1/images/menu-item-vED.png
    - assets/page-1/images/ellipse-25-bg-XUu.png
    - assets/page-1/images/ellipse-33-bg-gMo.png
    - assets/page-1/images/ellipse-42-bg-EeD.png
    - assets/page-1/images/ellipse-12-bg-jwf.png
    - assets/page-1/images/auto-group-sklr.png
    - assets/page-1/images/ellipse-16-bg-WnV.png
    - assets/page-1/images/trash-Fvy.png
    - assets/page-1/images/ellipse-26-bg-C5X.png
    - assets/page-1/images/ellipse-27-bg-y6q.png
    - assets/page-1/images/ellipse-28-bg-WoK.png
    - assets/page-1/images/vector-Br9.png
    - assets/page-1/images/ellipse-15-bg-iiu.png
    - assets/page-1/images/icons-settingsfilled24px-wrZ.png
    - assets/page-1/images/trash-ncH.png
    - assets/page-1/images/ellipse-42-bg-4Rf.png
    - assets/page-1/images/ellipse-32-bg-Dv9.png
    - assets/page-1/images/vector-ms7.png
    - assets/page-1/images/ellipse-32-bg-Za1.png
    - assets/page-1/images/ellipse-14-bg-GWM.png
    - assets/page-1/images/circle-button-xY9.png
    - assets/page-1/images/vector-ANd.png
    - assets/page-1/images/ellipse-18-bg-iLh.png
    - assets/page-1/images/ellipse-45.png
    - assets/page-1/images/group-31-inu.png
    - assets/page-1/images/trash-9Mj.png
    - assets/page-1/images/group-31-XGM.png
    - assets/page-1/images/ellipse-42-bg-gTK.png
    - assets/page-1/images/ellipse-14-bg-dfX.png
    - assets/page-1/images/icons-settingsfilled24px-8X3.png
    - assets/page-1/images/ellipse-25-bg-zZ7.png
    - assets/page-1/images/ellipse-12-bg-F2H.png
    - assets/page-1/images/ellipse-13-bg-Rah.png
    - assets/page-1/images/ellipse-22-bg-Stq.png
    - assets/page-1/images/ellipse-43.png
    - assets/page-1/images/vector-j3f.png
    - assets/page-1/images/menu-item-HWZ.png
    - assets/page-1/images/ellipse-44.png
    - assets/page-1/images/ellipse-16-bg-1To.png
    - assets/page-1/images/ellipse-20-bg-ZWq.png
    - assets/page-1/images/ellipse-13-bg-Qcq.png
    - assets/page-1/images/group-28-Gcy.png
    - assets/page-1/images/ellipse-15-bg-Ka1.png
    - assets/page-1/images/group-28-8SD.png
    - assets/page-1/images/ellipse-33-bg-Emf.png
    - assets/page-1/images/group-28-1vZ.png
    - assets/page-1/images/ellipse-28-bg-ncR.png
    - assets/page-1/images/ellipse-20-bg-2iM.png
    - assets/page-1/images/vector-4Xb.png
    - assets/page-1/images/vector-hyB.png
    - assets/page-1/images/ellipse-17-bg-ALh.png
    - assets/page-1/images/ellipse-26-bg-fwf.png
    - assets/page-1/images/ellipse-22-bg-s45.png
    - assets/page-1/images/sky5.png
    - assets/page-1/images/ellipse-25-bg-CHF.png
    - assets/page-1/images/ellipse-24-bg-eQZ.png
    - assets/page-1/images/ellipse-27-bg-S4q.png
    - assets/page-1/images/ellipse-14-bg-WAM.png
    - assets/page-1/images/ellipse-33-bg-Ftd.png
    - assets/page-1/images/vector-keM.png
    - assets/page-1/images/rectangle-59-bg.png
    - assets/page-1/images/vector-nmF.png
    - assets/page-1/images/ellipse-20-bg-74m.png
    - assets/page-1/images/ellipse-25-bg-sfX.png
    - assets/page-1/images/ellipse-18-bg-Tq3.png
    - assets/page-1/images/ellipse-27-bg-Aqo.png
    - assets/page-1/images/vector-eRP.png
    - assets/page-1/images/ellipse-15-bg-Jnm.png
    - assets/page-1/images/vector-LPT.png
    - assets/page-1/images/ellipse-42-bg-Spy.png
    - assets/page-1/images/ellipse-21-bg-bHj.png
    - assets/page-1/images/ellipse-31-bg-FGm.png
    - assets/page-1/images/ellipse-30-bg-YfB.png
    - assets/page-1/images/ellipse-24-bg-3PX.png
    - assets/page-1/images/ellipse-23-bg-ubo.png
    - assets/page-1/images/ellipse-13-bg-YY1.png
    - assets/page-1/images/ellipse-29-bg-Qk9.png
    - assets/page-1/images/ellipse-16-bg-ze5.png
    - assets/page-1/images/vector-EkR.png
    - assets/page-1/images/ellipse-19-bg-cFB.png
    - assets/page-1/images/ellipse-12-bg-pK3.png
    - assets/page-1/images/ellipse-32-bg-suK.png
    - assets/page-1/images/ellipse-28-bg-tt1.png
    - assets/page-1/images/sk4-1.png
    - assets/page-1/images/sky1.png
    - assets/page-1/images/sky3.png
    - assets/page-1/images/sky2.png
    - assets/page-1/images/n-crd.png
    - assets/page-1/images/ellipse-49-kG9.png
    - assets/page-1/images/vector-PLu.png
    - assets/page-1/images/ellipse-24-bg-xZF.png
    - assets/page-1/images/vector-rJV.png
    - assets/page-1/images/menu-item-i3B.png
    - assets/page-1/images/rectangle-56-R7P.png
    - assets/page-1/images/icons-zcZ.png
    - assets/page-1/images/vector-7ah.png
    - assets/page-1/images/vector-NeM.png
    - assets/page-1/images/vector-vk9.png
    - assets/page-1/images/vector-kbj.png
    - assets/page-1/images/menu-item-WSm.png
    - assets/page-1/images/vector-1u3.png
    - assets/page-1/images/Background1.png
    - assets/page-1/images/Background2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
