// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKcWzr7HXc0kTJzWv2BPOsL5JxD2IHbo',
    appId: '1:779350213048:web:2a182d208cdc91e7fc0f4d',
    messagingSenderId: '779350213048',
    projectId: 'test-58e55',
    authDomain: 'test-58e55.firebaseapp.com',
    storageBucket: 'test-58e55.appspot.com',
    measurementId: 'G-C1D3WSKWBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9E0ox8dAAA2Tv_sDOs0YnwHiwySy1aY',
    appId: '1:779350213048:android:316d0cd1e2c46322fc0f4d',
    messagingSenderId: '779350213048',
    projectId: 'test-58e55',
    storageBucket: 'test-58e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxhLt5CRFPBx6Ut7t1AOrHoDC8PQ99GQ',
    appId: '1:779350213048:ios:15d8567557f05598fc0f4d',
    messagingSenderId: '779350213048',
    projectId: 'test-58e55',
    storageBucket: 'test-58e55.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxhLt5CRFPBx6Ut7t1AOrHoDC8PQ99GQ',
    appId: '1:779350213048:ios:15d8567557f05598fc0f4d',
    messagingSenderId: '779350213048',
    projectId: 'test-58e55',
    storageBucket: 'test-58e55.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
